Categories:
  - Writing
License: Apache-2.0
AuthorName: Lawal Abiola
AuthorEmail: mshdabiola@gmail.com
AuthorWebSite: https://github.com/mshdabiola
SourceCode: https://github.com/mshdabiola/kmtemplate
IssueTracker: https://github.com/mshdabiola/kmtemplate/issues
Changelog: https://github.com/mshdabiola/kmtemplate/releases

AutoName: Kmtemplate

RepoType: git
Repo: https://github.com/mshdabiola/kmtemplate.git
Binaries: https://github.com/mshdabiola/kmtemplate/releases/download/%v/app-fossReliant-release-unsigned-signed.apk

Builds:
  - versionName: 1.2.16
    versionCode: 17
    commit: d54b2d56832b99cb4defa910b3a40826d9df175b
    subdir: app
    sudo:
      - echo "deb https://deb.debian.org/debian trixie main" > /etc/apt/sources.list.d/trixie.list
      - apt-get update
      - apt-get install -y -t trixie openjdk-21-jdk-headless
      - update-alternatives --auto java
    gradle:
      - fossReliant
    prebuild:
      - cd ..
      - gradle removeFirebaseReferences
      - gradle downgradeBuildLogicAndAgp
    scandelete:
      - build-logic/convention/build

AllowedAPKSigningKeys: 7966373797459065b77517aadbecc04b484abcf693d23ef1a6ccfb9556868750

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: gradle/libs.versions.toml|versionCode = "(\d+)"|.|versionName = "([\d.]+)"
CurrentVersion: 1.2.16
CurrentVersionCode: 17
