Categories:
  - Writing
License: Apache-2.0
AuthorName: Lawal Abiola
AuthorEmail: mshdabiola@gmail.com
AuthorWebSite: https://github.com/mshdabiola
SourceCode: https://github.com/mshdabiola/kmtemplate
IssueTracker: https://github.com/mshdabiola/kmtemplate/issues
Changelog: https://github.com/mshdabiola/kmtemplate/releases

AutoName: Kmtemplate

RepoType: git
Repo: https://github.com/mshdabiola/kmtemplate.git
Binaries: https://github.com/mshdabiola/kmtemplate/releases/download/%v/app-fossReliant-release-unsigned-signed.apk

Builds:
  - versionName: 1.2.18
    versionCode: 25
    commit: 4a85e995048686a919363e66d336ba2239479d2c
    sudo:
      - echo "deb https://deb.debian.org/debian trixie main" > /etc/apt/sources.list.d/trixie.list
      - apt-get update
      - apt-get install -y -t trixie openjdk-21-jdk-headless
      - update-alternatives --auto java
      - export CPUS_MAX=6
      - export CPUS=$(getconf _NPROCESSORS_ONLN)
      - for (( c=$CPUS_MAX; c<$CPUS; c++ )) ; do echo 0 > /sys/devices/system/cpu/cpu$c/online
        ; done
    gradle:
      - yes
    output: app/build/outputs/apk/fossReliant/release/app-fossReliant-release-unsigned.apk
    prebuild:
      - gradle clean
      - gradle removeFirebaseReferences
      - gradle downgradeBuildLogicAndAgp
    scandelete:
      - build-logic/convention/build
    build:
      - mkdir upstream
      - pushd upstream
      - curl -L -o upstream.apk https://github.com/mshdabiola/kmtemplate/releases/download/$$VERSION$$/app-fossReliant-release-unsigned-signed.apk
      - unzip -q upstream.apk
      - export upstreamhash=$(sha256sum assets/dexopt/baseline.prof|cut -d " " -f1)
      - popd
      - for i in {1..10}; do gradle clean assembleFossReliantRelease; mkdir local;
        pushd local; unzip -q ../app/build/outputs/apk/fossReliant/release/app-fossReliant-release-unsigned.apk;
        export localhash=$(sha256sum assets/dexopt/baseline.prof|cut -d " " -f1);
        [[ $localhash == $upstreamhash ]] && break ; popd; rm -fr local; done

AllowedAPKSigningKeys: 7966373797459065b77517aadbecc04b484abcf693d23ef1a6ccfb9556868750

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: gradle/libs.versions.toml|versionCode = "(\d+)"|.|versionName = "([\d.]+)"
CurrentVersion: 1.2.18
CurrentVersionCode: 25
