# These are supported funding model platforms

github: mshdabiola # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: mshdabiola # Replace with a single Ko-fi username
liberapay: mshdabiola # Replace with a single Liberapay username
buy_me_a_coffee: mshdabiola # Replace with a single Buy Me a Coffee username
