name: Bump Version Name and Code

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get tag name
        id: tag
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          # Remove leading 'v' if present
          TAG_NAME=${TAG_NAME#v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Update versionName and increment versionCode
        run: |
          # Set variables
          VERSION_NAME="${{ steps.tag.outputs.tag_name }}"
          # Update versionName
          sed -i -E "s/(versionName\s*=\s*")[^"]+(\")/\1$VERSION_NAME\2/" gradle/libs.versions.toml
          # Increment versionCode
          CODE=$(grep -Eo 'versionCode\s*=\s*"?[0-9]+"?' gradle/libs.versions.toml | grep -Eo '[0-9]+')
          NEW_CODE=$((CODE + 1))
          sed -i -E "s/(versionCode\s*=\s*")?[0-9]+("?)/\1$NEW_CODE\2/" gradle/libs.versions.toml

      - name: Commit and push changes
        run: |
          git add gradle/libs.versions.toml
          git commit -m "chore: set versionName to ${{ steps.tag.outputs.tag_name }} and bump versionCode" || echo "No changes to commit"
          git push
