name: Release Windows and Linux Hydraulic Conveyor

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run setVersionFromTag
        run: setVersionFromTag -PnewVersionName=${{ github.ref_name }}

      - name: Build jar
        run: ./gradlew createReleaseDistributable

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v18.1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      - name: Update Foss Reliant Badging
        run: ./gradlew updateFossReliantReleaseBadging

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          title: "chore: Bump Version name and code  "
          body: "Bumps  Version name and code  "
          branch: "bump-version-name-and-code"
          branch-suffix: short-commit-hash
          delete-branch: true
          base: develop
          signoff: false
          token: ${{ secrets.TOKEN }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
