name:  Release Android and Web

on:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write
  packages: write

jobs:
  android:
    name: Build and  Deploy Android Pre Release
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version
      # 2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run setVersionFromTag
        run: ./gradlew setVersionFromTag -PnewVersionName=${{ github.ref_name }}

      - name: Build  google play release variant apk
        run: ./gradlew assembleGooglePlayRelease

      - name: Sign google play APK
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: app/build/outputs/apk/googlePlay/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY2 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Remove Firebase References
        run: ./gradlew removeFirebaseReferences

      - name: Build foss reliant release variant apk
        run: ./gradlew assembleFossReliantRelease

      - name: Sign foss reliant APK
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: app/build/outputs/apk/fossReliant/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY2 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Draft Release
        uses: ncipollo/release-action@v1.18.0
        with:
          allowUpdates: true
          artifacts: "app/build/outputs/apk/**/**/**/*.apk,app/build/outputs/mapping/**/**/*.txt"
          # token: ${{ secrets.TOKEN }}
          generateReleaseNotes: true
          bodyFile: distribution/whatsnew/whatsnew-en-US
          prerelease: false

  web:
    name: Build and  Deploy Web Pre Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: kotlinUpgradeYarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build web app
        run: ./gradlew wasmJsBrowserDistribution

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: compose-web # The branch the action should deploy to.
          FOLDER: app/build/dist/wasmJs/productionExecutable # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

