name: Set Version from Tag

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
  workflow_dispatch:

jobs:
  set-version-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get tag name and parse versionCode
        id: tag
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          # Remove leading 'v' if present
          TAG_NAME=${TAG_NAME#v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          # Remove dots to get versionCode (e.g., 1.2.9 -> 129)
          VERSION_CODE=$(echo "$TAG_NAME" | tr -d '.')
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Update versionName and versionCode
        run: |
          VERSION_NAME="${{ steps.tag.outputs.tag_name }}"
          VERSION_CODE="${{ steps.tag.outputs.version_code }}"
          # Update versionName
          sed -i -E "s/(versionName\s*=\s*")[^"]+(\")/\1$VERSION_NAME\2/" gradle/libs.versions.toml
          # Update versionCode
          sed -i -E "s/(versionCode\s*=\s*")?[0-9]+("?)/\1$VERSION_CODE\2/" gradle/libs.versions.toml

      - name: Commit and push changes
        run: |
          git add gradle/libs.versions.toml
          git commit -m "chore: set versionName to ${{ steps.tag.outputs.tag_name }} and versionCode to ${{ steps.tag.outputs.version_code }} from tag" || echo "No changes to commit"
          git push
