name: Test

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
     
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Bump version code
        id: bump_version_code
        run: |
          ./gradlew bumpVersionCode -PnewVersionName=${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          commit-message: Update Revision
          committer: revision[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: revision-update
          base: develop
          delete-branch: true
          title: 'Revision Update'
          body: |
            This PR updates the revision of the project to the latest version.
            It is automatically generated by the workflow.
          labels: |
            auto-generated
            revision-update
